### PR TITLE
fix: send attachments without content type

### LINKED ISSUE #955: Allow MIME detection for crashpad attachments in the backend
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Attach a JSON file and try to view it within the issue page. The preview option is greyed out with the text: `Attachment cannot be previewed`

A user got around this by adding `contentType`. 
It's a property on the attachment object
const filename = 'XXX.json';
const contentType = 'application/json'; // helps show Preview in Sentry
hint.attachments = hint.attachments || [];
hint.attachments.push({ filename, data, contentType });

We should try to derive the content type from the file name. 

### Expected Result

Can view the payload in the issue. 

### Actual Result

Screenshot 2023-10-11 at 4 30 07 PM

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by supervacuus**
This fixes https://github.com/getsentry/sentry-native/issues/955 together with the merged/deployed relay change here: https://github.com/getsentry/relay/pull/3225

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]

File: util/net/http_multipart_builder.cc [hunk 1]
```diff
@@ -169,10 +169,15 @@ std::unique_ptr<HTTPBodyStream> HTTPMultipartBuilder::GetBodyStream() {
   for (const auto& pair : file_attachments_) {
     const FileAttachment& attachment = pair.second;
     std::string header = GetFormDataBoundary(boundary_, pair.first);
+#ifdef SENTRY_MODIFIED
```
Comment (csk-ableton) [inline util/net/http_multipart_builder.cc:172]: @supervacuus are clients expected to compile with `SENTRY_MODIFIED`? I can't find this flag anywhere, neither in this repo nor in sentry-native.

Comment (supervacuus) [reply util/net/http_multipart_builder.cc:172]: Nope, the definition is only a marker against changes from upstream. Since `SENTRY_MODIFIED` is not defined, only the `#else` will be generated while the upstream code is excluded.
